//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Random_File.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonDangKy
    {
        public string MaHDDK { get; set; }
        public string IDSIM { get; set; }
        public Nullable<decimal> ChiPhiDangKy { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual ThongTinSIM ThongTinSIM { get; set; }
    }
}
